# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
project_id = "jeevpuagctpmpodjbziu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[studio]
enabled = true
api_url = "https://jeevpuagctpmpodjbziu.supabase.co"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:*",
    "https://*.gitpod.io",
    "https://*.gitpod.io/**/*"
]